### ISSUE TITLE
examples/xdp-log does not compile

### ISSUE THREAD

**Issue by devinrsmith** [aya-rs/book#216]
examples/xdp-log does not compile:

```
error[E0061]: this function takes 2 arguments but 1 argument was supplied
  --> xdp-log/build.rs:14:5
   |
14 |     aya_build::build_ebpf([ebpf_package])
   |     ^^^^^^^^^^^^^^^^^^^^^---------------- argument #2 of type `Toolchain<'_>` is missing
   |
note: function defined here
  --> /home/user/.cargo/git/checkouts/aya-c5ab473414e1dedb/6d36fe1/aya-build/src/lib.rs:25:8
   |
25 | pub fn build_ebpf(packages: impl IntoIterator<Item = Package>, toolchain: Toolchain) -> Result<()> {
   |        ^^^^^^^^^^
help: provide the argument
   |
14 |     aya_build::build_ebpf([ebpf_package], /* Toolchain<'_> */)
   |                          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

For more information about this error, try `rustc --explain E0061`.
error: could not compile `xdp-log` (build script) due to 1 previous error
warning: build failed, waiting for other jobs to finish...
```

Looks like this is caused by https://github.com/aya-rs/aya/pull/1228

**Comment by hynseok** [comment]
Would it be okay if I try to fix this issue? 

#217

**Comment by devinrsmith** [comment]
Fixed by https://github.com/aya-rs/book/pull/218
